# Generated by Django 5.1.1 on 2024-10-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_data',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='profilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profilePic')),
                ('fkey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.signup_data')),
            ],
        ),
    ]
